[project]
name = "m2_nlp_meta_chu"
version = "0.1.0"
description = "Analyse des abstracts du CHU dans le cadre d'un projet M2."
readme = "README.md"
authors = [
    { name = "Adrien Albaladejo", email = "adrien.albaladejo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "biopython>=1.88",
    "nltk>=3.10.3",
    "pandas>=3.0.5",
    "spacy>=3.8.16",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
m2-nlp-meta-chu = "m2_nlp_meta_chu:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
